version: '3'
services:
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "8080:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: root@root.com
            PGADMIN_DEFAULT_PASSWORD: root
            PGADMIN_LISTEN_PORT: 80
        restart: always
        volumes:
            - pgadmin-data:/var/lib/pgadmin/data
        links:
            - "db:pgsql-server"
    db:
        image: postgres:12.1
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: social_media
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
    service:
        build:
            context: ./service
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./service/config:/app/config
            - ./service/src:/app/src
            - ./service/test:/app/test
            - ./service/build/
        ports:
            - "3001:3001"
        restart: always
    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./ui:/app
        ports:
            - "3000:3000"
        stdin_open: true

volumes: 
    db-data:
    pgadmin-data: